- name: configure cart server
  hosts: cart
  become: yes
  tasks:
  - name: enable nodejs 20
    ansible.builtin.command: dnf module enable nodejs:20 -y
  
  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: creating system user roboshop
    ansible.builtin.user:
      name: roboshop
      system: true
      home: /app
      shell: /sbin/nologin
      comment: "Roboshop system user"
  
  - name: delete directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: create directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: delete cart zip file
    ansible.builtin.file:
      path: /tmp/cart.zip
      state: absent

  - name: download cart 
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
      dest: /tmp/cart.zip 
  
  - name: unarchive cart
    ansible.builtin.unarchive:
      src: /tmp/cart.zip
      dest: /app
      remote_src: yes
  
  - name: install dependencies
    community.general.npm:
      path: /app

  - name: copy cart service
    ansible.builtin.template:
      src: cart.service
      dest: /etc/systemd/system/cart.service

  - name: daemon-reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: start cart
    ansible.builtin.service:
      name: cart
      state: restarted
      enabled: yes
